### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by cleesmith** [crohr/pkgr#35]
I have this in my .pkgr.yml:

```
addons:
  - mysql
targets:
  ubuntu-12.04:
    dependencies:
      - mysql-common
      - libpq5
      - libxslt1.1
      - libreadline5
      - libmysqlclient18
      - libevent-core-2.0-5
      - libevent-extra-2.0-5
after_install: packaging/debian/postinst
```

... but I get this error:

```
sudo dpkg -i cg-oneview_4.1.4-20140721194532_amd64.deb 
Selecting previously unselected package cg-oneview.
(Reading database ... 52818 files and directories currently installed.)
Unpacking cg-oneview (from cg-oneview_4.1.4-20140721194532_amd64.deb) ...
dpkg: dependency problems prevent configuration of cg-oneview:
 cg-oneview depends on libpq5; however:
  Package libpq5 is not installed.
 cg-oneview depends on libxslt1.1; however:
  Package libxslt1.1 is not installed.
 cg-oneview depends on libreadline5; however:
  Package libreadline5 is not installed.
 cg-oneview depends on libevent-core-2.0-5; however:
  Package libevent-core-2.0-5 is not installed.
 cg-oneview depends on libevent-extra-2.0-5; however:
  Package libevent-extra-2.0-5 is not installed.
dpkg: error processing cg-oneview (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead ...
Errors were encountered while processing:
 cg-oneview
```

Suggestions on how to handle dependencies ?  ... other than doing them before hand.

Also, why is libpq5 a dependency as I'm using mysql and not postgres ?

Also, is .pkgr.yml and the packaging folder required in the rails app for pkgr to work ?
Thanks
