### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by rijnhard** [crohr/pkgr#67]
I have a really unexplained error

`.pkgr.yml`

``` yaml
buildpack: https://github.com/heroku/heroku-buildpack-php.git#master
env:
  - STACK=cedar

targets:
  centos-6:
    build_dependencies:
      - readline
      - readline-devel
```

which solves the readline.so.5 error

``` bash
====== Attempt #1
-----> Fetching repository
Cloning into '/tmp/d20150522-24106-1mjf170/input'...
-----> Restoring cache
-----> Starting packaging process
-----> Fetching buildpack https://github.com/heroku/heroku-buildpack-php.git at master
-----> PHP app
 !     ERROR: Couldn't parse composer.lock; it must be valid JSON.
       Run 'composer update' to have it re-generated by Composer.
     ! ERROR: compile failed
       ! FAILED.
         Failure during packaging
       ! Please contact support.
```

And I composer updated, and checked with jsonlint, it is valid and both the `composer.json` and `composer.lock` are valid and in the root directory

**Comment by WiR3D-kNiGhT** [comment]
So my current logic is that thats something to do with Bob being used for the json parsing. 
Adding more build-deps hasn't helped yet. 

```yaml
targets:
  centos-6:
    build_dependencies:
      - readline
      - readline-devel
      - python
      - python-sphinx
      - python-setuptools
      - python-simplejson
```

But going to setup a local anvil and pkgr to see if I can fix things.
