### ISSUE TITLE
Default dependencies does not work

### ISSUE THREAD

**Issue by boskiv** [crohr/pkgr#80]
In yml file I have bith default dependencies and target specific dependencies, but after build my package contains only specific.

build command:
```
pkgr package ./frontend --debug --name=valo --auto --maintainer=support@iqreserve.ru --vendor=IQReserve --version=1.3 --iteration=%build.counter% --description="Valo 1.2" --homepage="http://iqreserve.ru"

```

yml:
```
dependencies:
  - imagemagick
  - valo-backend
  - valo-block-storage
  - valo-node-storage
  - valo-messaging
targets:
  ubuntu-14.04:
    dependencies:
      - nginx-extras
  centos-7:
    dependencies:
      - nginx >= 1.9.4
build_dependencies:
  - nodejs-legacy
  - npm
```

check:
```
[teamcity@ip-172-31-30-60 valo-server]$ rpm -qRp valo-1.3-%build.counter%.x86_64.rpm 
openssl
readline
libxml2
libxslt
libevent
postgresql-libs
mysql-libs
sqlite
nginx >= 1.9.4
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
[teamcity@ip-172-31-30-60 valo-server]$ 
```

**Comment by crohr** [comment]
@boskiv it's what is expected. Target-specific values take precedence over default values. Either duplicate all common dependencies in the targets, or use YAML references to avoid the duplication.

**Comment by boskiv** [comment]
Can you show me example of YML reference ?

**Comment by crohr** [comment]
For instance:

```yaml
targets:
  ubuntu-14.04:
    dependencies:
      - imagemagick
      - valo-backend
      - valo-block-storage
      - valo-node-storage
      - valo-messaging
      - nginx-extras
  centos-7:
    dependencies:
      - imagemagick
      - valo-backend
      - valo-block-storage
      - valo-node-storage
      - valo-messaging
      - nginx >= 1.9.4
build_dependencies:
  - nodejs-legacy
  - npm
```
